
###
https://jsonplaceholder.typicode.com/posts



###
https://jsonplaceholder.typicode.com/posts?userId=1


## _spPageContextInfo
# https://docs.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0&tabs=http

###
https://graph.microsoft.com/v1.0/sites/0fb72536-930e-400d-8dfe-5ed6411f3664/lists/87a448c5-0bfd-42a2-b370-d5eef68212c8/items?expand=fields

###
https://graph.microsoft.com/v1.0/sites/0fb72536-930e-400d-8dfe-5ed6411f3664/lists/87a448c5-0bfd-42a2-b370-d5eef68212c8/items/{item-id}/driveItem
